language: python
env:
  - LUA="lua=5.3"
python:
  - "3.8"
before_install:
  - pip install hererocks
  - pip install -U git+git://github.com/ajusa/lovebrew.git
  - hererocks lua_install -r^ --$LUA
  - export PATH=$PATH:$PWD/lua_install/bin
  - sudo apt-get -y install libzip-dev
install:
  - wget https://github.com/devkitPro/pacman/releases/download/v1.0.2/devkitpro-pacman.amd64.deb &&
    sudo dpkg -i devkitpro-pacman.deb
  - sudo dkp-pacman --noconfirm -Syu  
  - sudo dkp-pacman --noconfirm -S switch-dev 3ds-dev devkit-env
# there is probably a script that sets all of these, but yolo
  - export DEVKITPRO=/opt/devkitpro
  - export DEVKITARM=${DEVKITPRO}/devkitARM
  - export DEVKITPPC=${DEVKITPRO}/devkitPPC
  - export PATH=${DEVKITPRO}/tools/bin:$PATH
  - luarocks install moonscript
  - luarocks install busted
  - luarocks install alfons
  - luarocks install --server=http://luarocks.org/dev love-release
  - wget https://github.com/TurtleP/LovePotion/releases/download/2.0.0-pre3/LovePotion-Switch-68923d0.zip
  - unzip LovePotion-Switch-*
  - mkdir -p bin
  - mv LovePotion.elf bin/switch.elf
script:
  - alfons test
  - alfons build
  - lovebrew
  - mv VNDS-LOVE.nro build
deploy:
  provider: releases
  api_key:
    secure: ndpG9UpUBc4SMHUCaJn2aQmeP6ODBNPsEz/+RLwAbxdleJ6kFPjRQv1pGf5fpbJUhE5XZx+4XZkwPu5eTKAI2mjNQReyXNnoenM5dN/b8oJVO8GntPEkRh7TCL8Ss9FST4J6W7m4ejf/T1qqQmQAUGGd8ZGp6649h7KnUcrNPqURcWAn0DcUdBJQlqtCCK7Rt11B5tm9g2lIEwP1TaxYcD6DJl86qoSwj9Rx0L7lWXwBA7wq6OBfU19/vrxMBO9J6URL0fkaFnlCuwbted36IJ6rE8J/PhXdDOD7kVVHE2R8mwBohBh7LtpxTb1XsO5/1lCP6do2njM73YfOqdvU3LBp39jJfM8Y3uP2mcQZYfJIghLTC0WvrqdYz571Ejn3RgFkbwCl62jz18zyLo5VBUe9E0711Rc6JvXkWFs1sUbn9lBqQIO2ukoWVGVskIiSD27hWWWMDxxzpfrGUeRkN0RKQvXDA5Yil30CT2HF7GkDlMMttw5XpV81fAB+yfZn8UKoAz8lwIKavy2R25RS7odpDnQxRdkAq2FOldGAPDGuPd92o+q+aXwz/oMYjH6EgMm+WlFT2EglyXjU56W10iPx9ifE5mC7xqFubaYLMV41f02s5WYoPYEBoc8ax47EyrxHZ/ErPqJRf25ERMccPIRSe40x2NpVMuCKLziSw2E=
  file_glob: true
  file: build/*
  on:
    repo: ajusa/VNDS-LOVE
    tags: true
  skip_cleanup: 'true'
#after_script:
#- luacov
