language: python

env:
  - LUA="lua=5.3"
before_install:
  - pip install hererocks
  - hererocks lua_install -r^ --$LUA
  - export PATH=$PATH:$PWD/lua_install/bin
install:
  - luarocks install moonscript
  - luarocks install busted
  - luarocks install cluacov
  - luarocks install alfons
script:
  - alfons test
after_script:
  - luacov