language: c

env:
  global:
    - LUAROCKS=2.2.2
  matrix:
    - LUA=lua5.3
before_install:
  - source .travis/setenv_lua.sh
  - luarocks install moonscript
  - luarocks install busted
  - luarocks install cluacov
  - luarocks install luacheck

script:
  - busted -c tests.moon

after_script:
  - luacov
  - bash <(curl -s https://codecov.io/bash)