# This is a basic workflow to help you get started with Actions

name: VNDS-LOVE

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container:
      image: devkitpro/devkita64_devkitarm
      options: --cpus 2
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      - name: Update System
        run: |
          # Hack to get setup-python to work on act
          if [ ! -f "/etc/lsb-release" ] ; then
            echo "DISTRIB_RELEASE=18.04" > /etc/lsb-release
          fi
          dkp-pacman --needed --noconfirm -S switch-dev devkit-env
          curl -sL https://deb.nodesource.com/setup_14.x | sudo bash -
          echo "deb http://ftp.debian.org/debian sid main" >> /etc/apt/sources.list
          apt update
          apt-get -t sid -y install liblua5.3-dev lua5.3 zip libzip-dev nodejs libc6 libc6-dev libc6-dbg
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8.0'
      - name: OS Dependencies
        run: |
          # Install Python
          pip3 install lovebrew
          wget https://luarocks.org/releases/luarocks-3.5.0.tar.gz
          tar zxpf luarocks-3.5.0.tar.gz
          cd luarocks-3.5.0
          ./configure && make && make install
          cd ..

      - name: Lua Dependencies
        run: |
          luarocks install moonscript
          luarocks install busted
          luarocks install alfons
          luarocks install love-release
          wget https://github.com/TurtleP/LovePotion/releases/download/2.0.0-rc1/Nintendo.Switch-162bfdd.zip
          # wget https://github.com/TurtleP/LovePotion/releases/download/2.0.0-rc1/LovePotion-3DS-162bfdd_patch2.zip
          unzip Nintendo.Switch-*
          mkdir -p bin
          mv LovePotion.elf bin/switch.elf
          # unzip LovePotion-3DS-*
          # mv LovePotion.elf bin/3ds.elf
      - name: Tests
        run: alfons test
      - name: Build
        run: |
          mkdir -p /github/home/.lovepotion/
          touch /github/home/.lovepotion/.first_run
          alfons build
          lovebrew -v
          unzip -d build build/\*.zip
      - uses: actions/upload-artifact@v2
        with:
          name: Windows 32
          path: build/vnds-win32/
      - uses: actions/upload-artifact@v2
        with:
          name: Windows 64
          path: build/vnds-win64/
      - uses: actions/upload-artifact@v2
        with:
          name: MacOS
          path: build/vnds-macos.zip/
      - uses: actions/upload-artifact@v2
        with:
          name: LOVE
          path: build/vnds.love
      # - uses: actions/upload-artifact@v2
      #   with:
      #     name: 3DS
      #     path: build/VNDS-LOVE.3dsx
      - uses: actions/upload-artifact@v2
        with:
          name: Nintendo Switch
          path: build/VNDS-LOVE.nro

