name: Upload-to-Release
on: 
  release:
    types: [published]
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Download artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: main.yml
          workflow_conclusion: success
          commit: ${{ github.sha }}
      - name: Display structure of downloaded files
        run: ls -R
      - name: Rezip Files
        run: |
          zip -r Windows_64.zip "Windows 64"
          zip -r LOVE.zip "LOVE"
          zip -r Windows_32.zip "Windows 32"
          zip -r Nintendo_Switch.zip "Nintendo Switch"
          # zip -r 3DS.zip "3DS"
      - name: LOVE
        uses: JasonEtco/upload-to-release@master
        with:
          args: LOVE.zip application/zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload Windows_64
        uses: JasonEtco/upload-to-release@master
        with:
          args: Windows_64.zip application/zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload Windows 32
        uses: JasonEtco/upload-to-release@master
        with:
          args: Windows_32.zip application/zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # - name: Upload 3DS
      #   uses: JasonEtco/upload-to-release@master
      #   with:
      #     args: 3DS.zip application/zip
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload Nintendo Switch
        uses: JasonEtco/upload-to-release@master
        with:
          args: Nintendo_Switch.zip application/zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload OSX
        uses: JasonEtco/upload-to-release@master
        with:
          args: MacOS/vnds-macos.zip application/zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
